export enum AuthorizationResource {
  PERSON = 'PERSON',
  TENANT = 'TENANT',
  MEMBERSHIP = 'MEMBERSHIP',
  ROLE = 'ROLE',
  ROLE_ASSIGNMENT = 'ROLE_ASSIGNMENT',
  PERMISSION = 'PERMISSION',
  PERMISSION_ASSIGNMENT = 'PERMISSION_ASSIGNMENT',
}
